### ISSUE TITLE
Keyboard Keys Issue

### ISSUE THREAD

**Issue by kushagra765** [jaychandra6/hos-x86#1]
When your OS loads and if you type any word and hold the backspace key it doesn't remove the word typed but the keyboard cursor goes up and if you press the up arrow key it removes the words from your OS heading if the cursor is below it.

***Operating System***:
Linux Mint Cinnamon

***Emulator***:
QEMU 4.2.1

**Comment by 0jk6** [comment]
I did a lazy implementation of the backspace function in my VGA driver(will update that soon) and also initialized other keyboard keys like capslock to a space character. And talking about backspace, I thought of moving back and then replacing the characters while typing.(just like how insert key on keyboard annoys us all the time in terminal). Will fix that as soon as possible.

**Comment by kushagra765** [comment]
Alright!

**Comment by 0jk6** [comment]
@kushagra765 hey, I just fixed the backspace in the screen.c file, it should now work fine. :)

**Comment by kushagra765** [comment]
@jaychandra6 The backspace key works but if you hold the backspace key it erases everything on the screen!

**Comment by 0jk6** [comment]
Yeah, that's for another time. Lol

**Comment by kushagra765** [comment]
Lol!
